apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.service.name }}-tls-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.service.name }}-tls-secret
    app.kubernetes.io/component: tls-secret
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.secret.tls.crt }}
  tls.key: {{ .Values.secret.tls.key }}
