apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.service.name }}-api
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.service.name }}-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.service.name }}-api
        app.kubernetes.io/component: backend-api
    spec:
      containers:
        - name: login-api
          image: login-api:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "128Mi"
              cpu: "64m"
            limits:
              memory: "128Mi"
          ports:
            - containerPort: 8081
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 5
