apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}-cluster
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.service.name }}-cluster
    app.kubernetes.io/component: login-service
    monitoring: enabled
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ .Values.service.name }}-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8081
