kube-prometheus-stack:
  grafana:
    adminPassword:
    service:
      type: ClusterIP
      port: 80
    ingress:
      enabled: false
    sidecar:
      dashboards:
        enabled: true
    extraVolumes:
      - name: grafana-dashboard-login
        configMap:
          name: monitor-grafana-dashboard-login
    extraVolumeMounts:
      - name: grafana-dashboard-login
        mountPath: /tmp/dashboards/login-service-dashboard.json
        subPath: login-service-dashboard.json

  prometheus:
    service:
      type: ClusterIP
    prometheusSpec:
      serviceMonitorSelector:
        matchLabels:
          release: prometheus
      storageSpec:
        volumeClaimTemplate:
          spec:
            accessModes: [ "ReadWriteOnce" ]
            resources:
              requests:
                storage: 2Gi
