apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: non-resource-role-binding
subjects:
  - kind: User
    name: user-a
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: non-resource-get-role
  apiGroup: rbac.authorization.k8s.io

